title: Public Neocloud Services Comparison
email: kjrstory@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple cloud comparison chart of all the cloud services offered by the major public cloud vendors globally. 
url: "https://kjrstory.github.io" 
baseurl: "/neocloud_comparison"    
github_username:  kjrstory
linkedin_username:  kjrstory

theme: minima
