name: Build & Deploy Jekyll

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- YAML 문법 검사 ---
      - name: YAML lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: _data
          config_file: .yamllint.yml

      # --- (Gemfile이 있다면) 루비 + 번들러 ---
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true      # Gemfile이 없으면 이 스텝은 건너뜀

      # --- Jekyll 빌드 ---
      - uses: actions/jekyll-build-pages@v1    # => ./_site 생성

      # --- 결과물 업로드 (필수) ---
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site           # _site 내부만 tar → root UID 파일 미포함
          # name 생략 시 기본값 "github-pages"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment          # environment.url에 쓰려면 id 필요


